"""Add ip_address to Session model

Revision ID: 663a700b4503
Revises: 8d9b9fa19564
Create Date: 2025-08-29 16:14:52.467935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '663a700b4503'
down_revision = '8d9b9fa19564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###
