"""Add privacy_consent and cognome to Lead model

Revision ID: 8d9b9fa19564
Revises: 8dfe49212492
Create Date: 2025-08-29 15:27:19.156279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d9b9fa19564'
down_revision = '8dfe49212492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('privacy_consent', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_column('privacy_consent')

    # ### end Alembic commands ###
