"""Add default value to caratteristiche_json in Property

Revision ID: 943d9516a332
Revises: 663a700b4503
Create Date: 2025-08-30 10:03:52.628275

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '943d9516a332'
down_revision = '663a700b4503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=6), nullable=False))
        batch_op.add_column(sa.Column('expiry', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('lead_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.create_foreign_key(None, 'leads', ['lead_id'], ['id'])
        batch_op.drop_column('hash_codice')
        batch_op.drop_column('tentativi')
        batch_op.drop_column('email')
        batch_op.drop_column('scade_il')

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column('caratteristiche_json',
               existing_type=sqlite.JSON(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.alter_column('caratteristiche_json',
               existing_type=sqlite.JSON(),
               nullable=True)

    with op.batch_alter_table('otps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scade_il', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('tentativi', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('hash_codice', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('lead_id')
        batch_op.drop_column('expiry')
        batch_op.drop_column('code')

    # ### end Alembic commands ###
