"""Remove role column from User model

Revision ID: b8db6874123b
Revises: 36d14660b741
Create Date: 2025-08-27 11:47:21.328151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8db6874123b'
down_revision = '36d14660b741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=80), nullable=False))
    # ### end Alembic commands ###
