"""Initial migration.

Revision ID: d84e42242ee8
Revises:
Create Date: 2025-08-25 07:52:42.547860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd84e42242ee8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cognome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('consensi_json', sa.JSON(), nullable=True),
    sa.Column('stato', sa.String(length=50), nullable=True),
    sa.Column('creato_il', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('hash_codice', sa.String(length=255), nullable=False),
    sa.Column('scade_il', sa.DateTime(), nullable=False),
    sa.Column('tentativi', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rif', sa.String(length=50), nullable=False),
    sa.Column('titolo', sa.String(length=200), nullable=False),
    sa.Column('tipologia', sa.String(length=100), nullable=True),
    sa.Column('zona', sa.String(length=100), nullable=True),
    sa.Column('indirizzo_parziale', sa.String(length=200), nullable=True),
    sa.Column('mq', sa.Integer(), nullable=True),
    sa.Column('prezzo_min', sa.Float(), nullable=True),
    sa.Column('prezzo_max', sa.Float(), nullable=True),
    sa.Column('stato', sa.String(length=50), nullable=True),
    sa.Column('caratteristiche_json', sa.JSON(), nullable=True),
    sa.Column('attivo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rif')
    )
    op.create_table('property_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('path_privato', sa.String(length=255), nullable=False),
    sa.Column('checksum', sa.String(length=255), nullable=True),
    sa.Column('creato_il', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('rif', sa.String(length=50), nullable=True),
    sa.Column('iniziata_il', sa.DateTime(), nullable=True),
    sa.Column('completata_il', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('domanda_id', sa.String(length=100), nullable=True),
    sa.Column('domanda_testo', sa.String(length=500), nullable=True),
    sa.Column('risposta', sa.Text(), nullable=True),
    sa.Column('peso', sa.Integer(), nullable=True),
    sa.Column('fase', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('meta_json', sa.JSON(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('answers')
    op.drop_table('sessions')
    op.drop_table('property_assets')
    op.drop_table('properties')
    op.drop_table('otps')
    op.drop_table('leads')
    # ### end Alembic commands ###
